general:
  label: 基础设置
  items:
    sub_title:
      name: sub_title
      label: 二级标题
      type: text
      default: 'the site subtitle'
photos:
  label: 图库设置
  items:
    photoTitle:
      name: photoTitle
      label: 标题
      type: text
    photodes:
      name: photodes
      label: 简述
      type: textarea
sns:
  label: 社交资料
  items:
    github:
      name: github
      label: Github
      type: text
    wechat:
      name: wechat
      label: wechat
      type: text
    bilibili:
      name: bilibili
      label: bilibili
      type: text
    mail:
      name: mail
      label: mail
      type: text
